/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo.examen2.modelo;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;

/**
 *
 * @author hdavi
 */
public class venPrestamosVigentes extends javax.swing.JFrame {

    /**
     * Creates new form vBlog
     * @param pBlog
     */
    public venPrestamosVigentes(Coopena pMaster) {
        
        this.master = pMaster;
        
       master.getClientes().forEach((nCliente) -> {
              listClientes.addItem(nCliente.getNombre());
       });
       
       
       master.getClientes().get(0).getPrestamos().forEach((nPrestamo) -> {
           model.addElement(nPrestamo.getNumPrestamo());

       });
       
       jList1.setModel(model);
               
       
        
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jSeparator1 = new javax.swing.JSeparator();
        esquina = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        listClientes = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        fechaTentativa = new javax.swing.JLabel();
        numPrestamo = new javax.swing.JLabel();
        fechaCuota = new javax.swing.JLabel();
        fechaAutorizacion = new javax.swing.JLabel();
        valorPrestamo = new javax.swing.JLabel();
        nombSolicitante2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        titulo.setText("Prestamos Vigentes");
        jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 230, 40));

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 190, 250));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 10, 300));

        esquina.setText("  ");
        jPanel1.add(esquina, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 380, 30, -1));

        jLabel5.setText("Prestamos");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel6.setText("Fecha Tentativa");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, -1, -1));

        jLabel7.setText("Numero de Prestamo");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, -1));

        jLabel8.setText("Solicitante");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, -1, -1));

        jLabel9.setText("Valor del Prestamo");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));

        jLabel10.setText("Fecha de Cuota");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, -1, -1));

        jLabel11.setText("Fecha de Autorizacion");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, -1, -1));

        listClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listClientesActionPerformed(evt);
            }
        });
        jPanel1.add(listClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 50, -1));

        jLabel1.setText("Cliente Actual");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));
        jPanel1.add(fechaTentativa, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 100, 20));
        jPanel1.add(numPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 100, 20));
        jPanel1.add(fechaCuota, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 100, 20));
        jPanel1.add(fechaAutorizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 100, 20));
        jPanel1.add(valorPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 100, 20));
        jPanel1.add(nombSolicitante2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 100, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        
      master.getClientes().get(0).getPrestamos().forEach((nPrestamo) -> {
           model.addElement(nPrestamo.getNumPrestamo());
           if(nPrestamo.getNumPrestamo() == (Integer.parseInt(jList1.getSelectedValue()))){
               fechaCuota.setText(nPrestamo.getSolicitante().getNombre());
               numPrestamo.setText((Integer.toString(nPrestamo.getNumPrestamo())));
               fechaAutorizacion.setText(nPrestamo.getFechaAutorizacion());
               fechaTentativa.setText(nPrestamo.getFechaTentativa());
               valorPrestamo.setText((Integer.toString(nPrestamo.getValPrestamo())));
               fechaCuota.setText(nPrestamo.getFechasDePago());
               
                  
            }

       });
        
        jLabel1.setVisible(true);
        fechaTentativa.setVisible(true);
        numPrestamo.setVisible(true);
      
       
    }//GEN-LAST:event_jList1MouseClicked

    private void listClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listClientesActionPerformed

    
    
    private Coopena master;
    private DefaultListModel model = new DefaultListModel();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel esquina;
    private javax.swing.JLabel fechaAutorizacion;
    private javax.swing.JLabel fechaCuota;
    private javax.swing.JLabel fechaTentativa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> listClientes;
    private javax.swing.JLabel nombSolicitante2;
    private javax.swing.JLabel numPrestamo;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel valorPrestamo;
    // End of variables declaration//GEN-END:variables
}
